### PR TITLE
FE: Switching Icon Library

### PR DESCRIPTION
**Pull request by benniloidl**
See commits

### CODE REVIEW

**Comment by Jozys** [comment]
Maybe you should merge the main content into your branch, because your frontend tests are failing, because of an old error inside the react tests. Currently merging is blocked, because the tests are failing.

**Comment by benniloidl** [comment]
> Maybe you should merge the main content into your branch, because your frontend tests are failing, because of an old error inside the react tests. Currently merging is blocked, because the tests are failing.

Merging is currently blocked because of a missing review. The tests will succeed once the pull request has been closed.

**Comment by Jozys** [comment]
> Merging is currently blocked due to a missing review. The tests will succeed once the pull request has been closed.
It is also blocked because of the fact that not all tests are successfull.
I will add a review to this.

**Review by Jozys — APPROVED** [review]
The PR looks good. I am not sure, if everyone is happy with the new icons. In general I approve these PR.

**Pull request merged**
